version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install Back-End Dependencies
          command: "npm run backend:install"
      - run:
          name: Back-End Build
          command: "npm run backend:build"
      - run:
          name: Install Front-End Dependencies
          command: "npm run frontend:install"
      - run:
          name: Front-End Build
          command: "npm run frontend:build"
      - run:
          name: Deploy Backend
          command: "npm run backend:deploy"
      - run:
          name: Deploy Frontend
          command: "npm run frontend:deploy"
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
